name: vit_iqa
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-11.8.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1=1_gnu
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - cryptography=41.0.2
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0
  - cuda-compiler=11.8.0
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cuobjdump=11.8.86
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=11.8.86
  - cuda-documentation=11.8.86
  - cuda-driver-dev=11.8.89
  - cuda-gdb=11.8.86
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.8.89
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.8.86
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.8.86
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-nvvp=11.8.87
  - cuda-profiler-api=11.8.86
  - cuda-runtime=11.8.0
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.8.0
  - cuda-tools=11.8.0
  - cuda-visual-tools=11.8.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - ffmpeg=4.3
  - filelock=3.9.0
  - freetype=2.12.1
  - gds-tools=1.4.0.31
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - icu=58.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - ipykernel=6.25.0
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.9
  - jupyter_core=5.3.0
  - jupyter_server=1.23.4
  - jupyterlab_pygments=0.1.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libpng=1.6.39
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=3.1
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nsight-compute=2022.3.0.22
  - numpy=1.25.2
  - numpy-base=1.25.2
  - openh264=2.1.1
  - openssl=3.0.10
  - packaging=23.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - platformdirs=2.5.2
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyzmq=23.2.0
  - readline=8.2
  - requests=2.31.0
  - send2trash=1.8.0
  - setuptools=68.0.0
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.3.2
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - contourpy==1.1.0
      - cycler==0.11.0
      - einops==0.6.1
      - fonttools==4.42.0
      - joblib==1.3.2
      - kiwisolver==1.4.4
      - matplotlib==3.7.2
      - pandas==2.0.3
      - pillow==10.0.0
      - pyparsing==3.0.9
      - pytz==2023.3
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - threadpoolctl==3.2.0
      - tzdata==2023.3